In [1]:
import pandas as pd
import numpy as np

In [2]:
#Let's try with street names that contain the seasons
#and let's use the big GBG dataset

GBG_all = pd.read_csv("GBG all highways simplified.csv")

/Users/silfa/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (2,4,10,11,12,13,16,17,19,22,23,24,26,27,28,29,30,31,32,33,35,37,38,39,40,42,43,44,45,46,47,50,51,52,54,55,58,59,60,61,63,64,66,67,68,69,70,71,72,73,74,75,77,78,79,80,81,82,83,85,86,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,116,117,119,120,121,122,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,144,145,146,147,148,149,151,153,154,155,158,162,163,164,165,166,167,168,169,171,172,173,174,175,176,177,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,198,199,200,201,202,203,204,205,206,207,208,210,211,212,216,217,218,219,220,221,222,223,224,226,227,228,229,230,231,233,234,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
#Get a smaller dataset that only contains relevant columns

GBG_subset=GBG_all[["@id", "highway", "name", "highway", "FID"]]
GBG_subset[:5]

           @id        highway           name        highway          FID
0  way/4040302       motorway  Kungälvsleden       motorway  way/4040302
1  way/4040303       motorway            NaN       motorway  way/4040303
2  way/4040436  motorway_link            NaN  motorway_link  way/4040436
3  way/4040439       motorway            NaN       motorway  way/4040439
4  way/4040441       motorway            NaN       motorway  way/4040441

In [4]:
#Load the csv with the GBG_cluster "culture"
GBG_cluster_culture = pd.read_csv("GBG_cluster_culture.csv")
GBG_cluster_culture.head()

FileNotFoundError: [Errno 2] No such file or directory: 'GBG_cluster_culture.csv'

In [ ]:
#Make a list out of this column
GBG_cluster_culture_list = GBG_cluster_culture["culture"].tolist()
print(GBG_cluster_culture_list)

In [ ]:
#Create a list of our conditions
culture_conditions_list = []
for item in GBG_cluster_culture_list:
    culture_conditions_list.append((GBG_subset["name"].str.startswith(item) == True))

#print (culture_conditions_list)

In [ ]:
#Create a list of the values we want to assign for each condition
#We want to actually give all those streets the value "culture", so we need a list of the same number
#of items
culture_values = []
for item in GBG_cluster_culture_list:
    culture_values.append("culture")

print(len(culture_values))
print(len(GBG_cluster_culture_list))

In [ ]:
#Now, create a new column and use np.select to assign values to it using our list as arguments
#GBG_subset["category"] = np.select(list of conditions, category values, "other")
#We don't want to fill in "other", since this will be filled with other categories later

GBG_subset["category"] = np.select(culture_conditions_list, culture_values)

In [ ]:
GBG_subset.to_csv("GBG_subset with category.csv")

In [ ]:
#Now repeat this with another category!

In [ ]:
#Load the csv with the GBG_cluster "radio"
GBG_cluster_radio = pd.read_csv("GBG_cluster_radio.csv")
GBG_cluster_radio.head()

In [ ]:
#Make a list out of this column
GBG_cluster_radio_list = GBG_cluster_radio["radio"].tolist()
print(GBG_cluster_radio_list)

In [5]:
#Create a list of our conditions
radio_conditions_list = []
for item in GBG_cluster_radio_list:
    radio_conditions_list.append((GBG_subset["name"].str.startswith(item) == True))

#print (culture_conditions_list)

NameError: name 'GBG_cluster_radio_list' is not defined

In [6]:
#Create a list of the values we want to assign for each condition
#We want to actually give all those streets the value "radio", so we need a list of the same number
#of items
radio_values = []
for item in GBG_cluster_radio_list:
    radio_values.append("radio")

print(len(radio_values))
print(len(GBG_cluster_radio_list))

NameError: name 'GBG_cluster_radio_list' is not defined

In [7]:
#Now, create a new column and use np.select to assign values to it using our list as arguments
#GBG_subset["category"] = np.select(list of conditions, category values, "other")
#We don't want to fill in "other", since this will be filled with other categories later

GBG_subset["category"] = np.select(radio_conditions_list, radio_values)

ValueError: select with an empty condition list is not possible

In [8]:
GBG_subset.to_csv("GBG_subset with category updated.csv")

In [9]:
GBG_subset_noblanks = GBG_subset[~GBG_subset["name"].isnull()] #get rid of empty values in the names column

In [10]:
GBG_subset_noblanks.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17703 entries, 0 to 61071
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   @id      17703 non-null  object
 1   highway  17703 non-null  object
 2   name     17703 non-null  object
 3   highway  17703 non-null  object
 4   FID      17703 non-null  object
dtypes: object(5)
memory usage: 829.8+ KB

In [11]:
GBG_subset_noblanks_culture = GBG_subset_noblanks[GBG_subset_noblanks.name.isin(GBG_cluster_culture_list)]

NameError: name 'GBG_cluster_culture_list' is not defined

In [97]:
GBG_subset_noblanks_culture.head()

               @id       highway           name       highway           FID
211    way/4330717   residential  Mandolingatan   residential   way/4330717
212    way/4330719  unclassified     Musikvägen  unclassified   way/4330719
213    way/4330720   residential     Musikvägen   residential   way/4330720
1200   way/9400681   residential     Pianogatan   residential   way/9400681
2793  way/24481236   residential     Orgelgatan   residential  way/24481236

In [98]:
GBG_subset_noblanks_radio = GBG_subset_noblanks[GBG_subset_noblanks.name.isin(GBG_cluster_radio_list)]

In [99]:
GBG_subset_noblanks_radio.head()

             @id       highway               name       highway          FID
156  way/4303214   residential         Radiovägen   residential  way/4303214
342  way/4550704  unclassified     Bildradiogatan  unclassified  way/4550704
343  way/4550705   residential  Kondensatorsgatan   residential  way/4550705
371  way/4730731   residential        Signalgatan   residential  way/4730731
830  way/7356866   residential         Kabelgatan   residential  way/7356866

In [ ]:
GBG_subset_noblanks.loc[GBG_subset_noblanks_culture, "culture"] = True

## loc
loc is for filtering rows and columns **by label**, i.e. for rows by index, for columns by column names.

df.loc[what rows do I want, what columns do I want]

For row 0 and all columns: df.loc[0, :]

You can also pass a list in, e.g. for rows 0, 3 and 7: df.loc[[0,3,7], :]

For continuous rows: df.loc[0:3, :] --> inclusive on both sides

For specific columns by name: df.loc[: , ["city", "state"]]

### loc with Boolean conditions

E.g. if you want to select all rows where city = Oakland: df[df.city == "Oakland]

But the same thing can be done with .loc:

df.loc[ufo.city == "Oakland, :]

Advantage with the .loc method: it will not cause problems related to chained indexing!

## iloc

iloc is for filtering rows and columns **by integer position**

e.g. all rows and columns in position 0 and 3: df.iloc[:, [0, 3]]

For continuous columns: df.iloc[:, [0:3]] --> exclusive on the right side!

## Applying a function to a dataframe

### map
Map is a series method. 

### apply
Apply is both a series and a dataframe method. It applies a function to each element in a series or dataframe.

In [102]:
höga = pd.read_csv("HBG Högaborg residential.csv")
höga.head()

,@id,highway,maxspeed,name,source,FID,surface,oneway,motor_vehicle,psv,cycleway:left,cycleway:right,access
0,way/26336094,residential,50,Närlundavägen,Bing,way/26336094,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,way/26336095,residential,40,Sofiebergsvägen,NaN,way/26336095,asphalt,NaN,NaN,NaN,NaN,NaN,NaN
2,way/30813280,residential,40,Sturzen-Beckers gata,NaN,way/30813280,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,way/30813307,residential,40,Gustav Adolfs gata,NaN,way/30813307,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,way/32203823,residential,40,Faktorsgatan,NaN,way/32203823,asphalt,NaN,NaN,NaN,NaN,NaN,NaN

In [103]:
selection = ["Närlundavägen", "Sofiebergsvägen"]
selection2 = ["Gustav Adolfs gata", "Faktorsgatan", "Gasverksgatan"]

In [104]:
def get_category(series, selection_list):
    if series in selection_list:
        return True

In [107]:
höga.name.apply(get_category, selection_list=selection2)

0     None
1     None
2     None
3     True
4     True
5     None
6     None
7     None
8     None
9     None
10    None
11    None
12    None
13    None
14    None
15    None
16    None
17    None
18    None
19    None
20    None
21    None
22    None
23    None
24    None
25    None
26    None
27    True
28    None
29    True
30    None
31    None
32    True
33    None
34    None
35    None
36    None
37    None
38    None
39    None
40    None
41    None
42    None
43    None
44    None
45    None
Name: name, dtype: object

In [125]:
#Filtering for names in a certain list
#boolean_series = df.fruit.isin(value_lis

selection1_höga = höga.loc[höga.name.isin(selection), :]

In [129]:
def f(row):
    if row['name'] in selection:
        val = "selection1"
    elif row['name'] in selection2:
        val = "selection2"
    else:
        val = "other"
    return val

In [131]:
höga['cateegory'] = höga.apply(f, axis=1)
höga.head()

,@id,highway,maxspeed,name,source,FID,surface,oneway,motor_vehicle,psv,cycleway:left,cycleway:right,access,cateegory
0,way/26336094,residential,50,Närlundavägen,Bing,way/26336094,NaN,NaN,NaN,NaN,NaN,NaN,NaN,selection1
1,way/26336095,residential,40,Sofiebergsvägen,NaN,way/26336095,asphalt,NaN,NaN,NaN,NaN,NaN,NaN,selection1
2,way/30813280,residential,40,Sturzen-Beckers gata,NaN,way/30813280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,other
3,way/30813307,residential,40,Gustav Adolfs gata,NaN,way/30813307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,selection2
4,way/32203823,residential,40,Faktorsgatan,NaN,way/32203823,asphalt,NaN,NaN,NaN,NaN,NaN,NaN,selection2

In [4]:
gbg = pd.read_csv("Unique GBG street names.csv")
gbg.head(20)

    Unnamed: 0      street names
0            0     Kungälvsleden
1            2        Boråsleden
2            3        Gråbovägen
3            4      Hjällbovägen
4            5     Alingsåsleden
5            6   Kungsbackaleden
6            7     Stora Nygatan
7            8   Östra Larmgatan
8            9   Östra Hamngatan
9           10     Lilla Nygatan
10          11        Slussgatan
11          12         Nya Allén
12          13   Norra Allégatan
13          14         Parkgatan
14          15    Trädgårdsgatan
15          16   Bastionsplatsen
16          17  Lilla Kungsgatan
17          18    Grönsakstorget
18          19   Södra Larmgatan
19          20       Kungstorget

In [5]:
radio_cluster = pd.read_csv("cluster_radio.csv")
culture_cluster = pd.read_csv("cluster_culture.csv")
space_cluster = pd.read_csv("cluster_space.csv")
professions_cluster = pd.read_csv("cluster_professions.csv")
colors_cluster = pd.read_csv("cluster_colors.csv")
animals_cluster = pd.read_csv("cluster_animals.csv")
industrial_cluster = pd.read_csv("cluster_industrial.csv")
doctors_cluster = pd.read_csv("cluster_doctors.csv")
food_cluster = pd.read_csv("cluster_food.csv")
weather_cluster = pd.read_csv("cluster_weather.csv")
holidays_cluster = pd.read_csv("cluster_holidays.csv")
flora_cluster = pd.read_csv("cluster_flora.csv")
gems_cluster = pd.read_csv("cluster_gems.csv")
radio_cluster.head()

              radio
0     Åttarörsgatan
1  Bandfiltersgatan
2    Bildradiogatan
3     Elektrongatan
4      Ettrörsgatan

In [6]:
#Turn into list
culture_list = culture_cluster["culture"].tolist()
radio_list = radio_cluster["radio"].tolist()
space_list = space_cluster["space"].tolist()
professions_list = professions_cluster["professions"].tolist()
colors_list = colors_cluster["colors"].tolist()
animals_list = animals_cluster["animals"].tolist()
industrial_list = industrial_cluster["industrial"].tolist()
doctors_list = doctors_cluster["doctors"].tolist()
food_list = food_cluster["food"].tolist()
weather_list = weather_cluster["weather"].tolist()
holidays_list = holidays_cluster["holidays"].tolist()
flora_list = flora_cluster["flora"].tolist()
gems_list = gems_cluster["gems"].tolist()

In [7]:
def check_category(row):
    if row['street names'] in culture_list:
        cat = "culture"
    elif row['street names'] in radio_list:
        cat = "radio"
    elif row['street names'] in space_list:
        cat = "space"
    elif row['street names'] in professions_list:
        cat = "professions"
    elif row['street names'] in colors_list:
        cat = "colors"
    elif row['street names'] in animals_list:
        cat = "animal"
    elif row['street names'] in industrial_list:
        cat = "industrial"
    elif row['street names'] in doctors_list:
        cat = "doctors"
    elif row['street names'] in food_list:
        cat = "food"
    elif row['street names'] in weather_list:
        cat = "weather"
    elif row['street names'] in holidays_list:
        cat = "holidays"
    elif row['street names'] in flora_list:
        cat = "flora"
    elif row['street names'] in gems_list:
        cat = "gems"
    else:
        cat = "other"
    return cat

In [8]:
gbg['category'] = gbg.apply(check_category, axis=1)

In [9]:
gbg_new = gbg.rename(columns={"street names":"name"})

In [10]:
gbg_new.head()

   Unnamed: 0           name category
0           0  Kungälvsleden    other
1           2     Boråsleden    other
2           3     Gråbovägen    other
3           4   Hjällbovägen    other
4           5  Alingsåsleden    other

In [11]:
gbg_new.to_csv("gbg_test3.csv")